---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi  # Specify 5 GiB of storage
  accessModes:
    - ReadWriteOnce  # Access mode (single node read/write)
  hostPath:
    path: {{ vars.LOCAL_PATH }}  # Adjust for your Windows/Linux environment
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Request the same size as the PV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: db-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ secrets.MYSQL_PASSWORD }}  # MySQL root password
        - name: MYSQL_DATABASE
          value: {{ vars.MYSQL_DB }}  # Database name
        volumeMounts:
        - mountPath: /var/lib/mysql  # MySQL data directory
          name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc  # Reference the PVC
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306  # MySQL default port
      name: mysql-port
  selector:
    app: mysql
  type: ClusterIP
